# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
default = User.create(name: "DEFAULT_USER", password: "Emanuel", admin: true, email: "example@something.com")
Category.create(name: "Physical")
Category.create(name: "Sleep")
Category.create(name: "Mood")
Category.create(name: "Cognition")
Category.create(name: "Leisure")
Category.create(name: "Social")
Category.create(name: "Spirituality")
Category.create(name: "Finances")
Category.create(name: "Household")
Category.create(name: "Self-esteem")
Category.create(name: "Independence")
Category.create(name: "Identity")
Category.create(name: "Work")
Category.create(name: "Education")


default_questionnaire = Questionnaire.create(name: "Quality of Life", user: default)
Question.create(body: "...had plenty of energy.", category: Category.find_by(name:"Physical"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had the right amount of exercise for me.", category: Category.find_by(name:"Physical"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt physically well.", category: Category.find_by(name:"Physical"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been content with my sex life.", category: Category.find_by(name:"Physical"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...awoken feeling refreshed.", category: Category.find_by(name:"Sleep"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no problems getting out of bed.", category: Category.find_by(name:"Sleep"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had about the right amount of sleep for me.", category: Category.find_by(name:"Sleep"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept a routine in my sleep-wake schedule.", category: Category.find_by(name:"Sleep"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt happy.", category: Category.find_by(name:"Mood"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed things as much as I usually do.", category: Category.find_by(name:"Mood"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt able to cope.", category: Category.find_by(name:"Mood"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt emotionally balanced.", category: Category.find_by(name:"Mood"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...thought clearly.", category: Category.find_by(name:"Cognition"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had good concentration.", category: Category.find_by(name:"Cognition"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no difficulties with my memory.", category: Category.find_by(name:"Cognition"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...made plans without difficulty.", category: Category.find_by(name:"Cognition"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed my leisure activities.", category: Category.find_by(name:"Leisure"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been interested in my leisure activities.", category: Category.find_by(name:"Leisure"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had fun during my leisure activities.", category: Category.find_by(name:"Leisure"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...expressed my creativity.", category: Category.find_by(name:"Leisure"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed spending time with other people.", category: Category.find_by(name:"Social"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been interested in my social relationships.", category: Category.find_by(name:"Social"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had meaningful friendships.", category: Category.find_by(name:"Social"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been able to share feelings or problems with a friend.", category: Category.find_by(name:"Social"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been satisfied with the spiritual side of my life.", category: Category.find_by(name:"Spirituality"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...expressed my spirituality as I wish.", category: Category.find_by(name:"Spirituality"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...practised my spirituality as I wish.", category: Category.find_by(name:"Spirituality"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept routine in my spiritual life.", category: Category.find_by(name:"Spirituality"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had enough money for basic needs.", category: Category.find_by(name:"Finances"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had enough money for extras.", category: Category.find_by(name:"Finances"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt secure about my current financial situation.", category: Category.find_by(name:"Finances"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no difficulties with debts.", category: Category.find_by(name:"Finances"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...done my daily household chores.", category: Category.find_by(name:"Household"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been organized around my home.", category: Category.find_by(name:"Household"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept my home tidy.", category: Category.find_by(name:"Household"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept my home clean.", category: Category.find_by(name:"Household"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt respected.", category: Category.find_by(name:"Self-esteem"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt accepted by others.", category: Category.find_by(name:"Self-esteem"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt as worthwhile as other people.", category: Category.find_by(name:"Self-esteem"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt able to cope with stigma.", category: Category.find_by(name:"Self-esteem"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a sense of freedom.", category: Category.find_by(name:"Independence"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt safe in my home environment.", category: Category.find_by(name:"Independence"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...traveled around freely (e.g., driving, using public transport).", category: Category.find_by(name:"Independence"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt others have allowed me my independence.", category: Category.find_by(name:"Independence"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a strong sense of self.", category: Category.find_by(name:"Identity"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a stable sense of what I’m really like.", category: Category.find_by(name:"Identity"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a clear idea of what I want and don’t want.", category: Category.find_by(name:"Identity"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...had control over my life.", category: Category.find_by(name:"Identity"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been confident in my abilities at work.", category: Category.find_by(name:"Work"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...met demands at work.", category: Category.find_by(name:"Work"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been satisfied with the quality of my work.", category: Category.find_by(name:"Work"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...been reliable at work.", category: Category.find_by(name:"Work"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed my educational activities.", category: Category.find_by(name:"Education"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt confident about finishing my educational activities.", category: Category.find_by(name:"Education"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...performed to my usual standards educationally.", category: Category.find_by(name:"Education"), questionnaire: default_questionnaire, default: true)
Question.create(body: "...organized my educational activities adequately.", category: Category.find_by(name:"Education"), questionnaire: default_questionnaire, default: true)
