# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
default = User.create(name: "DEFAULT_USER", password: "Emanuel", admin: true, email: "example@something.com")
default_questionnaire = Questionnaire.create(name: "Quality of Life", user: default)
Question.create(body: "...had plenty of energy.", category: "Physical", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had the right amount of exercise for me.", category: "Physical", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt physically well.", category: "Physical", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been content with my sex life.", category: "Physical", questionnaire: default_questionnaire, default: true)
Question.create(body: "...awoken feeling refreshed.", category: "Sleep", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no problems getting out of bed.", category: "Sleep", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had about the right amount of sleep for me.", category: "Sleep", questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept a routine in my sleep-wake schedule.", category: "Sleep", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt happy.", category: "Mood", questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed things as much as I usually do.", category: "Mood", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt able to cope.", category: "Mood", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt emotionally balanced.", category: "Mood", questionnaire: default_questionnaire, default: true)
Question.create(body: "...thought clearly.", category: "Cognition", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had good concentration.", category: "Cognition", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no difficulties with my memory.", category: "Cognition", questionnaire: default_questionnaire, default: true)
Question.create(body: "...made plans without difficulty.", category: "Cognition", questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed my leisure activities.", category: "Leisure", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been interested in my leisure activities.", category: "Leisure", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had fun during my leisure activities.", category: "Leisure", questionnaire: default_questionnaire, default: true)
Question.create(body: "...expressed my creativity.", category: "Leisure", questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed spending time with other people.", category: "Social", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been interested in my social relationships.", category: "Social", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had meaningful friendships.", category: "Social", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been able to share feelings or problems with a friend.", category: "Social", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been satisfied with the spiritual side of my life.", category: "Spirituality", questionnaire: default_questionnaire, default: true)
Question.create(body: "...expressed my spirituality as I wish.", category: "Spirituality", questionnaire: default_questionnaire, default: true)
Question.create(body: "...practised my spirituality as I wish.", category: "Spirituality", questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept routine in my spiritual life.", category: "Spirituality", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had enough money for basic needs.", category: "Finances", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had enough money for extras.", category: "Finances", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt secure about my current financial situation.", category: "Finances", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had no difficulties with debts.", category: "Finances", questionnaire: default_questionnaire, default: true)
Question.create(body: "...done my daily household chores.", category: "Household", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been organized around my home.", category: "Household", questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept my home tidy.", category: "Household", questionnaire: default_questionnaire, default: true)
Question.create(body: "...kept my home clean.", category: "Household", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt respected.", category: "Self-esteem", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt accepted by others.", category: "Self-esteem", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt as worthwhile as other people.", category: "Self-esteem", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt able to cope with stigma.", category: "Self-esteem", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a sense of freedom.", category: "Independence", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt safe in my home environment.", category: "Independence", questionnaire: default_questionnaire, default: true)
Question.create(body: "...traveled around freely (e.g., driving, using public transport).", category: "Independence", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt others have allowed me my independence.", category: "Independence", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a strong sense of self.", category: "Identity", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a stable sense of what I’m really like.", category: "Identity", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had a clear idea of what I want and don’t want.", category: "Identity", questionnaire: default_questionnaire, default: true)
Question.create(body: "...had control over my life.", category: "Identity", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been confident in my abilities at work.", category: "Work", questionnaire: default_questionnaire, default: true)
Question.create(body: "...met demands at work.", category: "Work", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been satisfied with the quality of my work.", category: "Work", questionnaire: default_questionnaire, default: true)
Question.create(body: "...been reliable at work.", category: "Work", questionnaire: default_questionnaire, default: true)
Question.create(body: "...enjoyed my educational activities.", category: "Education", questionnaire: default_questionnaire, default: true)
Question.create(body: "...felt confident about finishing my educational activities.", category: "Education", questionnaire: default_questionnaire, default: true)
Question.create(body: "...performed to my usual standards educationally.", category: "Education", questionnaire: default_questionnaire, default: true)
Question.create(body: "...organized my educational activities adequately.", category: "Education", questionnaire: default_questionnaire, default: true)
