# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
default = User.create(name: "DEFAULT_USER", password: "Emanuel", admin: true, email: "example@something.com")
Category.create(name: "Physical")
Category.create(name: "Sleep")
Category.create(name: "Mood")
Category.create(name: "Cognition")
Category.create(name: "Leisure")
Category.create(name: "Social")
Category.create(name: "Spirituality")
Category.create(name: "Finances")
Category.create(name: "Household")
Category.create(name: "Self-esteem")
Category.create(name: "Independence")
Category.create(name: "Identity")
Category.create(name: "Work")
Category.create(name: "Education")

default_questionnaire = Questionnaire.create(name: "Quality of Life", user: default, default: true)

Question.create(body: "...had plenty of energy.", category_id: Category.find_by(name:"Physical").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had the right amount of exercise for me.", category_id: Category.find_by(name:"Physical").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt physically well.", category_id: Category.find_by(name:"Physical").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been content with my sex life.", category_id: Category.find_by(name:"Physical").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...awoken feeling refreshed.", category_id: Category.find_by(name:"Sleep").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had no problems getting out of bed.", category_id: Category.find_by(name:"Sleep").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had about the right amount of sleep for me.", category_id: Category.find_by(name:"Sleep").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...kept a routine in my sleep-wake schedule.", category_id: Category.find_by(name:"Sleep").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt happy.", category_id: Category.find_by(name:"Mood").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...enjoyed things as much as I usually do.", category_id: Category.find_by(name:"Mood").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt able to cope.", category_id: Category.find_by(name:"Mood").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt emotionally balanced.", category_id: Category.find_by(name:"Mood").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...thought clearly.", category_id: Category.find_by(name:"Cognition").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had good concentration.", category_id: Category.find_by(name:"Cognition").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had no difficulties with my memory.", category_id: Category.find_by(name:"Cognition").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...made plans without difficulty.", category_id: Category.find_by(name:"Cognition").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...enjoyed my leisure activities.", category_id: Category.find_by(name:"Leisure").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been interested in my leisure activities.", category_id: Category.find_by(name:"Leisure").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had fun during my leisure activities.", category_id: Category.find_by(name:"Leisure").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...expressed my creativity.", category_id: Category.find_by(name:"Leisure").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...enjoyed spending time with other people.", category_id: Category.find_by(name:"Social").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been interested in my social relationships.", category_id: Category.find_by(name:"Social").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had meaningful friendships.", category_id: Category.find_by(name:"Social").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been able to share feelings or problems with a friend.", category_id: Category.find_by(name:"Social").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been satisfied with the spiritual side of my life.", category_id: Category.find_by(name:"Spirituality").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...expressed my spirituality as I wish.", category_id: Category.find_by(name:"Spirituality").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...practised my spirituality as I wish.", category_id: Category.find_by(name:"Spirituality").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...kept routine in my spiritual life.", category_id: Category.find_by(name:"Spirituality").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had enough money for basic needs.", category_id: Category.find_by(name:"Finances").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had enough money for extras.", category_id: Category.find_by(name:"Finances").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt secure about my current financial situation.", category_id: Category.find_by(name:"Finances").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had no difficulties with debts.", category_id: Category.find_by(name:"Finances").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...done my daily household chores.", category_id: Category.find_by(name:"Household").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been organized around my home.", category_id: Category.find_by(name:"Household").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...kept my home tidy.", category_id: Category.find_by(name:"Household").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...kept my home clean.", category_id: Category.find_by(name:"Household").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt respected.", category_id: Category.find_by(name:"Self.id-esteem"), questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt accepted by others.", category_id: Category.find_by(name:"Self.id-esteem"), questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt as worthwhile as other people.", category_id: Category.find_by(name:"Self.id-esteem"), questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt able to cope with stigma.", category_id: Category.find_by(name:"Self.id-esteem"), questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had a sense of freedom.", category_id: Category.find_by(name:"Independence").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt safe in my home environment.", category_id: Category.find_by(name:"Independence").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...traveled around freely (e.g., driving, using public transport).", category_id: Category.find_by(name:"Independence").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt others have allowed me my independence.", category_id: Category.find_by(name:"Independence").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had a strong sense of self.", category_id: Category.find_by(name:"Identity").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had a stable sense of what I’m really like.", category_id: Category.find_by(name:"Identity").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had a clear idea of what I want and don’t want.", category_id: Category.find_by(name:"Identity").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...had control over my life.", category_id: Category.find_by(name:"Identity").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been confident in my abilities at work.", category_id: Category.find_by(name:"Work").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...met demands at work.", category_id: Category.find_by(name:"Work").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been satisfied with the quality of my work.", category_id: Category.find_by(name:"Work").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...been reliable at work.", category_id: Category.find_by(name:"Work").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...enjoyed my educational activities.", category_id: Category.find_by(name:"Education").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...felt confident about finishing my educational activities.", category_id: Category.find_by(name:"Education").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...performed to my usual standards educationally.", category_id: Category.find_by(name:"Education").id, questionnaire: default_questionnaire, default: true, user: default)
Question.create(body: "...organized my educational activities adequately.", category_id: Category.find_by(name:"Education").id, questionnaire: default_questionnaire, default: true, user: default)


Rating.create(rating: 1, designation: "Disagree Strongly")
Rating.create(rating: 2, designation: "Disagree")
Rating.create(rating: 3, designation: "Neutral")
Rating.create(rating: 4, designation: "Agree")
Rating.create(rating: 1, designation: "Agree Strongly")
